name: Zip Files

on:
  push:
    branches:
    - master

  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@master

    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        filename: 'mumbleLinkAutoInstaller.zip'
        exclusions: '*.git*'

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          Changes in this Release
          - First Change
          - Second Change
        draft: false
        prerelease: false

    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "mumbleLinkAutoInstaller.zip"
        token: ${{ secrets.GITHUB_TOKEN }}