name: Zip Files

on:
  push:
    branches:
    - master

  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        filename: 'mumbleLinkAutoInstaller.zip'
        exclusions: '*.git*'
    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "mumbleLinkAutoInstaller.zip"
        token: ${{ secrets.GITHUB_TOKEN }}